pipeline {
    agent any
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    stages {
        stage('Requirements') {
            steps {
                // this step is required to make sure the script
                // can be executed directly in a shell
                sh('chmod +x ./ch2_version_control_systems/02_04_challenge_connect_jenkins_to_github/algorithm.sh')
            }
        }
        stage('Build') {
            steps {
                // the algorithm script creates a file named report.txt
                sh('./ch2_version_control_systems/02_04_challenge_connect_jenkins_to_github/algorithm.sh')

                // this step archives the report
                archiveArtifacts allowEmptyArchive: true,
                    artifacts: '*.txt',
                    fingerprint: true,
                    onlyIfSuccessful: true
            }
        }
    }
}
