pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: ['10','20','30','40','50','60','70','80','90'],
            description: 'Select the value for F(n) for the Fibonacci sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Setup') {
            steps {
                sh 'chmod +x ./ch2_version_control_systems/02_03_run_scripts_from_the_pipeline/fibonacci.sh'
            }
        }
        stage('Relative path') {
            steps {
                sh("./ch2_version_control_systems/02_03_run_scripts_from_the_pipeline/fibonacci.sh ${env.NUMBER}")
            }
        }
        stage('Full path') {
            steps {
                sh("${env.WORKSPACE}/ch2_version_control_systems/02_03_run_scripts_from_the_pipeline/fibonacci.sh ${env.NUMBER}")
            }
        }
        stage('Change directory') {
            steps {
                dir("${env.WORKSPACE}/ch2_version_control_systems/02_03_run_scripts_from_the_pipeline/"){
                    sh("./fibonacci.sh ${env.NUMBER}")
                }
            }
        }
    }
}
